blocks:
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks:
  - export_rhs_to_gcs
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: load_rhs_from_github
  retry_config: null
  status: executed
  timeout: null
  type: data_loader
  upstream_blocks: []
  uuid: load_rhs_from_github
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks:
  - wait_3_mins
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: export_rhs_to_gcs
  retry_config: null
  status: executed
  timeout: null
  type: data_exporter
  upstream_blocks:
  - load_rhs_from_github
  uuid: export_rhs_to_gcs
- all_upstream_blocks_executed: true
  color: blue
  configuration: {}
  downstream_blocks:
  - trigger_matching_pipeline
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: wait_3_mins
  retry_config: null
  status: updated
  timeout: null
  type: custom
  upstream_blocks:
  - export_rhs_to_gcs
  uuid: wait_3_mins
- all_upstream_blocks_executed: false
  color: null
  configuration: {}
  downstream_blocks: []
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: trigger_matching_pipeline
  retry_config: null
  status: updated
  timeout: null
  type: data_exporter
  upstream_blocks:
  - wait_3_mins
  uuid: trigger_matching_pipeline
cache_block_output_in_memory: false
callbacks: []
concurrency_config: {}
conditionals: []
created_at: '2024-04-05 05:12:03.829497+00:00'
data_integration: null
description: Fetch rhs data from github and store to GCS
executor_config: {}
executor_count: 1
executor_type: null
extensions: {}
name: rhs_data
notification_config: {}
remote_variables_dir: null
retry_config: {}
run_pipeline_in_one_process: false
settings:
  triggers: null
spark_config: {}
tags: []
type: python
uuid: rhs_data
variables_dir: /home/src/mage_data/blaithin
widgets: []
