version: '3'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    container_name: mage-${PROJECT_NAME}
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
      GCP_PROJECT: ${GCP_PROJECT}
      GOOGLE_APPLICATION_CREDENTIALS: /home/config/account_key.json
    ports:
      - 6789:6789
    volumes:
      - ../config:/home/config
      - .:/home/src/
    restart: on-failure:5
    deploy:
      resources:
        limits:
          cpus: '12'
          memory: 12G
        reservations:
          cpus: '6'
          memory: 6G