triggers:
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.725969+00:00
  name: Daily fetch of plant data from RHS for plant type - 1
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings:
    landing_time_enabled: false
  sla: null
  start_time: 2024-03-26 17:00:00
  status: active
  variables:
    plant_type: 1
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469
  name: Daily fetch of plant data from RHS for plant type - 2
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:01:00
  status: inactive
  variables:
    plant_type: 2
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 3
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:02:00
  status: active
  variables:
    plant_type: 3
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 4
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:03:00
  status: active
  variables:
    plant_type: 4
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 5
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:04:00
  status: active
  variables:
    plant_type: 5
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 6
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:05:00
  status: active
  variables:
    plant_type: 6
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 7
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:06:00
  status: active
  variables:
    plant_type: 7
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 8
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:07:00
  status: active
  variables:
    plant_type: 8
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 9
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:08:00
  status: active
  variables:
    plant_type: 9
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 10
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:09:00
  status: active
  variables:
    plant_type: 10
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 11
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:10:00
  status: active
  variables:
    plant_type: 11
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 12
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:11:00
  status: active
  variables:
    plant_type: 12
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 13
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:12:00
  status: active
  variables:
    plant_type: 13
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 14
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:13:00
  status: active
  variables:
    plant_type: 14
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 15
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:14:00
  status: active
  variables:
    plant_type: 15
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 16
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:15:00
  status: active
  variables:
    plant_type: 16
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 17
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:16:00
  status: active
  variables:
    plant_type: 17
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 18
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:17:00
  status: active
  variables:
    plant_type: 18
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 19
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:18:00
  status: active
  variables:
    plant_type: 19
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 20
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:19:00
  status: active
  variables:
    plant_type: 20
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469+00:00
  name: Daily fetch of plant data from RHS for plant type - 21
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:20:00
  status: active
  variables:
    plant_type: 21
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.847469
  name: Daily fetch of plant data from RHS for plant type - 22
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-26 17:21:00
  status: inactive
  variables:
    plant_type: 22
