blocks:
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks: []
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: intriguing melody
  retry_config: null
  status: not_executed
  timeout: null
  type: data_loader
  upstream_blocks: []
  uuid: intriguing_melody
cache_block_output_in_memory: false
callbacks: []
concurrency_config: {}
conditionals: []
created_at: '2024-04-03 10:33:03.533291+00:00'
data_integration: null
description: Match the RHS data to the product data
executor_config: {}
executor_count: 1
executor_type: null
extensions: {}
name: link_rhs_to_products
notification_config: {}
remote_variables_dir: null
retry_config: {}
run_pipeline_in_one_process: false
settings:
  triggers: null
spark_config: {}
tags: []
type: python
uuid: link_rhs_to_products
variables_dir: /home/src/mage_data/blaithin
widgets: []
