blocks:
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks:
  - combine_common_and_botanical_names
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: extract_plants
  retry_config: null
  status: executed
  timeout: null
  type: data_loader
  upstream_blocks: []
  uuid: extract_plants
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks:
  - transform_products
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: extract_products
  retry_config: null
  status: executed
  timeout: null
  type: data_loader
  upstream_blocks: []
  uuid: extract_products
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks:
  - match_product_to_plant
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: combine_common_and_botanical_names
  retry_config: null
  status: executed
  timeout: null
  type: transformer
  upstream_blocks:
  - extract_plants
  uuid: combine_common_and_botanical_names
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks:
  - match_product_to_plant
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: transform_products
  retry_config: null
  status: executed
  timeout: null
  type: transformer
  upstream_blocks:
  - extract_products
  uuid: transform_products
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks:
  - export_matches_to_gcs
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: match_product_to_plant
  retry_config: null
  status: executed
  timeout: null
  type: transformer
  upstream_blocks:
  - combine_common_and_botanical_names
  - transform_products
  uuid: match_product_to_plant
- all_upstream_blocks_executed: false
  color: null
  configuration: {}
  downstream_blocks:
  - trigger_dbt
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: export_matches_to_gcs
  retry_config: null
  status: executed
  timeout: null
  type: data_exporter
  upstream_blocks:
  - match_product_to_plant
  uuid: export_matches_to_gcs
- all_upstream_blocks_executed: false
  color: null
  configuration: {}
  downstream_blocks: []
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: trigger_dbt
  retry_config: null
  status: executed
  timeout: null
  type: data_exporter
  upstream_blocks:
  - export_matches_to_gcs
  uuid: trigger_dbt
cache_block_output_in_memory: false
callbacks: []
concurrency_config: {}
conditionals: []
created_at: '2024-04-03 10:33:03.533291+00:00'
data_integration: null
description: Match the RHS data to the product data
executor_config: {}
executor_count: 1
executor_type: null
extensions: {}
name: link_rhs_to_products
notification_config: {}
remote_variables_dir: null
retry_config: {}
run_pipeline_in_one_process: false
settings:
  triggers: null
spark_config: {}
tags: []
type: python
uuid: link_rhs_to_products
variables_dir: /home/src/mage_data/blaithin
widgets: []
