blaithin:
  target: default
  outputs:
    default:
      type: bigquery
      method: service-account
      project: {{env_var('GCP_PROJECT')}}
      dataset: blaithin
      threads: 4 # Must be a value of 1 or greater
      keyfile: {{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}