blaithin:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: 	{{ env_var('GCP_PROJECT') }}
      dataset: blaithin
      threads: 4
      keyfile: {{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}