triggers:
- envs: []
  last_enabled_at: 2024-03-28 06:30:27.725969
  name: Daily fetch of plant data from RHS for all plant types
  pipeline_uuid: rhs_urls
  schedule_interval: '@daily'
  schedule_type: time
  settings:
    create_initial_pipeline_run: true
    landing_time_enabled: false
    skip_if_previous_running: true
  sla: null
  start_time: 2024-03-26 17:00:00
  status: inactive
  variables:
    plant_types:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
