version: '3'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    container_name: mage-${PROJECT_NAME}
    env_file:
      -  .env
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
    ports:
      - 6789:6789
    volumes:
      - ../config:/home/config
      - ./data:/home/src/
      - ./app:/app/${PROJECT_NAME}/
    restart: on-failure:5